#ifndef CONVERTER_ERRORS_H
#define CONVERTER_ERRORS_H

enum Errors {
    INCOR_ARGS_NUM,
    OPEN_CFG_FILE,
    READ_CFG_FILE,
    OPTIONS_PARSER,
    NOT_ENOUGH_ITER = 100,
};

#endif //CONVERTER_ERRORS_H
